version: '3'
services:
  jasmine:
    build:
      context: .
      dockerfile: .docker/jasmine/Dockerfile
    container_name: jasmine-${COMPOSE_PROJECT_NAME}
    restart: always
    volumes:
      - .:/app
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
